Remove fallback routes
systemli/userli pull request #548
Opened 2024-01-14 16:16 UTC by 0x46616c6b

2024-01-14 17:53 UTC, 0x46616c6b commented on src/Admin/UserAdmin.php
> +    public function setMailCryptVar(string $mailCrypt): void
The parameter comes from an environment variable, so it will be a string.

2024-01-14 17:56 UTC, 0x46616c6b commented on composer.json
> +        "phpunit/phpunit": "^9.5",
See the configuration of testing in Symfony Docs: https://symfony.com/doc/5.x/testing.html

They recommend to install `symfony/test-pack` which also installes `phpunit/phpunit` and `symfony/css-selector`

2024-01-14 17:56 UTC, 0x46616c6b commented on config/packages/security.yaml
> +      - { path: "^/[a-z]{2,3}/init", roles: IS_AUTHENTICATED_ANONYMOUSLY }
I changed the regex for locales to `[a-z]{2,3}` because we also support `gsw`, which obviously has three characters.

2024-01-16 15:04 UTC, t2d requested changes
Thanks for working on this. The dependency changes in this PR are sadly not compatible with Debian 11 or 12. Can you please adjust?

2024-01-16 15:33 UTC, 0x46616c6b commented
> Thanks for working on this. The dependency changes in this PR are sadly not compatible with Debian 11 or 12. Can you please adjust?

I can not reproduce this and can't install a Debian VM. Can you point me in the direction of the problem? What is the issue?

2024-01-16 18:01 UTC, t2d approved these changes
Thanks, the change looks good. The only weird thing to me is that German `de/voucher` redirects to the English `/login`. I mean the site is easy to understand, but it kind of defeats the purpose of having a multi-lingual login side

2024-01-17 19:06 UTC, merged